# Generated by Django 5.1.4 on 2025-01-02 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budgetwise', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Update',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.CharField(help_text='Version number (e.g., v1.0.0)', max_length=20)),
                ('description', models.TextField(help_text='Description of the update')),
                ('release_date', models.DateField(help_text='Release date of the update')),
            ],
        ),
    ]
