# Generated by Django 5.1.4 on 2025-01-06 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budgetwise', '0003_remove_category_type_remove_category_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='budget',
            name='type',
            field=models.CharField(choices=[('income', 'Income'), ('expense', 'Expense')], max_length=10, null=True),
        ),
    ]
