# Generated by Django 5.1.4 on 2025-01-07 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budgetwise', '0006_account'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='auditlog',
            options={'verbose_name': 'Audit Log', 'verbose_name_plural': 'Audit Logs'},
        ),
        migrations.AlterModelOptions(
            name='profile',
            options={'verbose_name': 'Profile', 'verbose_name_plural': 'Profiles'},
        ),
        migrations.AlterModelOptions(
            name='savingsgoal',
            options={'verbose_name': 'Saving Goal', 'verbose_name_plural': 'Saving Goals'},
        ),
        migrations.AddField(
            model_name='savingsgoal',
            name='transactions',
            field=models.ManyToManyField(blank=True, related_name='savings_goals', to='budgetwise.transaction'),
        ),
    ]
