# Generated by Django 5.1.4 on 2025-01-13 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budgetwise', '0007_alter_auditlog_options_alter_profile_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='currency',
            field=models.CharField(choices=[('USD', 'Dollar'), ('EUR', 'Euro'), ('JPY', 'Japanese Yen'), ('GBP', 'Pound Sterling')], default='USD', max_length=3),
        ),
    ]
