# Generated by Django 5.1.4 on 2025-01-13 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budgetwise', '0008_alter_profile_currency'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='profile_picture',
            field=models.ImageField(default='media/profile_pictures/default.jpg', upload_to='media/profile_pictures'),
        ),
    ]
