# Generated by Django 5.1.4 on 2025-01-13 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budgetwise', '0012_alter_profile_profile_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='plan',
            field=models.CharField(choices=[('free', 'Free'), ('premium', 'Premium'), ('elite', 'Elite')], default='free', max_length=10),
        ),
    ]
