# Generated by Django 5.1.4 on 2025-01-14 14:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('budgetwise', '0013_profile_plan'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Account',
        ),
        migrations.AlterModelOptions(
            name='budget',
            options={'verbose_name': 'Budget', 'verbose_name_plural': 'Budgets'},
        ),
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'Category', 'verbose_name_plural': 'Categories'},
        ),
        migrations.AlterModelOptions(
            name='notification',
            options={'verbose_name': 'Notification', 'verbose_name_plural': 'Notifications'},
        ),
        migrations.AlterModelOptions(
            name='transaction',
            options={'verbose_name': 'Transaction', 'verbose_name_plural': 'Transactions'},
        ),
        migrations.AlterModelOptions(
            name='update',
            options={'verbose_name': 'Update', 'verbose_name_plural': 'Updates'},
        ),
        migrations.DeleteModel(
            name='AuditLog',
        ),
    ]
