# Generated by Django 5.1.4 on 2025-01-15 12:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('budgetwise', '0015_contactmessage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='savingsgoal',
            name='saved_amount',
        ),
    ]
