# Generated by Django 5.1.4 on 2025-01-15 14:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('budgetwise', '0018_budget_month_budget_year_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='budget',
            name='type',
        ),
    ]
