# Generated by Django 5.1.4 on 2025-01-15 15:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('budgetwise', '0019_remove_budget_type'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='budget',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='budget',
            name='category',
        ),
    ]
