# Generated by Django 5.1.4 on 2025-01-15 18:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('budgetwise', '0020_alter_budget_unique_together_remove_budget_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='timezone',
        ),
    ]
